<h1>Dashboard</h1>
<hr>
<div class="row-fluid">
    <div class="span8">
	<div class="accordion" id="accordion2">
	    <div class="accordion-group">
		<div class="accordion-heading">
		    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
			Aufgaben
		    </a>
		</div>
		<div id="collapseOne" class="accordion-body collapse in">
		    <div class="accordion-inner">
			xxx
		    </div>
		</div>
	    </div>
	</div>
    </div>

    <div class="span4">
	<div class="accordion" id="accordion2">
	    <div class="accordion-group">
		<div class="accordion-heading">
		    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
			News
		    </a>
		</div>
		<div id="collapseOne" class="accordion-body collapse in">
		    <div class="accordion-inner">
			Anim pariatur cliche...
		    </div>
		</div>
	    </div>
	</div>
    </div>
</div>

<div class="row-fluid">
    <div class="span8">
	<div class="accordion" id="accordion2">
	    <div class="accordion-group">
		<div class="accordion-heading">
		    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
			Projekte
		    </a>
		</div>
		<div id="collapseOne" class="accordion-body collapse in">
		    <div class="accordion-inner">
			xxx
		    </div>
		</div>
	    </div>
	</div>
    </div>

    <div class="span4">
	<div class="accordion" id="accordion2">
	    <div class="accordion-group">
		<div class="accordion-heading">
		    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
			Termine
		    </a>
		</div>
		<div id="collapseOne" class="accordion-body collapse in">
		    <div class="accordion-inner">
			Anim pariatur cliche...
		    </div>
		</div>
	    </div>
	</div>
    </div>
</div>