<?= $this->partial('project/subnav.phtml'); ?>

<h2>Aufgaben</h2>
<hr>
<div class="row-fluid" style="margin-bottom: 20px;">
    <div class="pull-right">
	<button class="btn btn-primary">Aufgabe anlegen</button>
    </div>
</div>

<div class="well">
    FILTER
</div>

<div class="well">
    <table class="table table-hover table-bordered table-striped" style="background-color: #ffffff;">
	<thead>
	    <tr>
		<th>ID</th>
		<th>Titel</th>
		<th>Begin</th>
		<th>Ende</th>
		<th>zul. geändert</th>
		<th>Mitarbeiter</th>
		<th>Prio</th>
		<th>Status</th>
		<th>Aufw. Ist</th>
		<th>Aufw. Soll</th>
		<th>Aktion</th>
	    </tr>
	</thead>
	<tbody>
	    <tr>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>
		    <div class="btn-group">
			<a class="btn btn-primary" href="./user/edit/1">edit</a>
			<button class="btn dropdown-toggle btn-primary" data-toggle="dropdown">
			    <span class="caret"></span>
			</button>
			<ul class="dropdown-menu">
			    <!-- <li><a href="./user/sulogin/1">SU-Login</a></li> -->
			    <li><a href="./user/disable/1">disable</a></li>
			    <li><a href="./user/delete/1">delete</a></li>
			</ul>
		    </div>
		</td>
	    </tr>
	    <tr>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>
		    <div class="btn-group">
			<a class="btn btn-primary" href="./user/edit/1">edit</a>
			<button class="btn dropdown-toggle btn-primary" data-toggle="dropdown">
			    <span class="caret"></span>
			</button>
			<ul class="dropdown-menu">
			    <!-- <li><a href="./user/sulogin/1">SU-Login</a></li> -->
			    <li><a href="./user/disable/1">disable</a></li>
			    <li><a href="./user/delete/1">delete</a></li>
			</ul>
		    </div>
		</td>
	    </tr>
	    <tr>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>...</td>
		<td>
		    <div class="btn-group">
			<a class="btn btn-primary" href="./user/edit/1">edit</a>
			<button class="btn dropdown-toggle btn-primary" data-toggle="dropdown">
			    <span class="caret"></span>
			</button>
			<ul class="dropdown-menu">
			    <!-- <li><a href="./user/sulogin/1">SU-Login</a></li> -->
			    <li><a href="./user/disable/1">disable</a></li>
			    <li><a href="./user/delete/1">delete</a></li>
			</ul>
		    </div>
		</td>
	    </tr>
	</tbody>
    </table>
</div>