<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<title><?php echo $this->class->config->base->title; ?></title>
	<base href="<?php echo $this->class->config->base->url; ?>" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta name="generator" content="charm" />
	<link rel="icon" href="favicon.ico" type="image/x-icon"/>
	<link rel="shortcut icon" href="favicon.ico" type="image/x-icon"/>
	<link rel="stylesheet" type="text/css" href="css/layout.css" media="all" />
</head>
<body class="login">
<div class="login-box">
	<img src="img/logo_b_bgw.png" alt="ChaRM" title="ChaRM" />
	<?php echo $this->form; ?>
	<p><?php echo $this->class->config->base->title ?> &copy; 2011</p>
</div>
</body>
</html>
