	<?php include('include/header.phtml'); ?>

<div class="content-box">
	<?php include('include/menu.phtml'); ?>
	<div class="content-box-body">

	<?php include('include/submenu.phtml'); ?>

<table class="listing" width="100%" border="0" cellpadding="0" cellspacing="0">
<tr class="listing-header">
	<td>Firma</td>
	<td>Anschrift</td>
	<td>Telefon</td>
	<td>Internet</td>
	<td>Aktion</td>
</tr>
<tr class="listing-search-row">
	<td><input type="text" name="" value="" /></td>
	<td><input type="text" name="" value="" /></td>
	<td><input type="text" name="" value="" /></td>
	<td><input type="text" name="" value="" /></td>
	<td><input type="text" name="" value="" /></td>
</tr>
<?php

if(is_array($this->companies)) {
	$x = 0;
	foreach($this->companies as $key => $value) {
		//echo '<li><a href="./address/editcompany/id/'.$value['id'].'">edit</a> - <a href="./address/showcompany/id/'.$value['id'].'">'.$value['name'].'</a></li>'."\n";
		echo '<tr onmouseover="Element.addClassName(this,\'listing-row-over\');" onmouseout="Element.removeClassName(this,\'listing-row-over\');" onclick="window.location = \'./address/showcompany/id/'.$value['id'].'\';" class="listing-row '.(($x == 0) ? 'listing-row-alternate' : '').'">
			<td><a href="./address/showcompany/id/'.$value['id'].'">'.$value['name'].'</a></td>
			<td>'.$value['street'].'<br />'.$value['zip'].'&nbsp;'.$value['city'].'</td>
			<td><a href="callto:'.$value['phone'].'">'.$value['phone'].'</a></td>
			<td>'.(($value['url']) ? 'Homepage: <a href="'.$value['url'].'">'.$value['url'].'</a><br />' : '').(($value['email']) ? 'Email: <a href="mailto:'.$value['email'].'">'.$value['email'].'</a>' : '') .'</td>
			<td><a href="./address/editcompany/id/'.$value['id'].'" class="button">bearbeiten</a><a href="./address/delcompany/id/'.$value['id'].'" class="button">l&ouml;schen</a></td>
		</tr>';
		if($x == 0) $x = 1;
		else $x = 0; 
	}
}
?>
</table>
	</div>
</div>
