<link rel='stylesheet' type='text/css' href='fullcalendar/fullcalendar.css' />
<link rel='stylesheet' type='text/css' href='fullcalendar/fullcalendar.print.css' media='print' />

<script type='text/javascript' src='http://code.jquery.com/ui/1.10.1/jquery-ui.js'></script>
<link rel='stylesheet' type='text/css' href='http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css' />

<script type='text/javascript' src='fullcalendar/fullcalendar.min.js'></script>
<script type='text/javascript'>

	$(document).ready(function() {

		var date = new Date();
		var d = date.getDate();
		var m = date.getMonth();
		var y = date.getFullYear();

		$('#calendar').fullCalendar({
			header: {
				left: 'month,agendaWeek,agendaDay',
				center: 'title',
				right: 'today prev,next'
			},
			editable: true,
			selectable: true,
			unselectAuto: true,
			dayClick: function(date, allDay, jsEvent, view) {
				if (allDay) {
				    alert('Clicked on the entire day: ' + date);
				}else{
				    alert('Clicked on the slot: ' + date);
				}

				alert('Coordinates: ' + jsEvent.pageX + ',' + jsEvent.pageY);
				alert('Current view: ' + view.name);

				// change the day's background color just for fun
				$(this).css('background-color', 'red');
			},
			eventClick: function(calEvent, jsEvent, view) {
				alert('Event: ' + calEvent.title);
				alert('Coordinates: ' + jsEvent.pageX + ',' + jsEvent.pageY);
				alert('View: ' + view.name);

				// change the border color just for fun
				$(this).css('border-color', 'red');
			},
			eventResize: function(event,dayDelta,minuteDelta,revertFunc) {
				alert(
				    "The end date of " + event.title + "has been moved " +
				    dayDelta + " days and " +
				    minuteDelta + " minutes."
				);

				if (!confirm("is this okay?")) {
				    revertFunc();
				}
			},
			eventDrop: function(event,dayDelta,minuteDelta,allDay,revertFunc) {
				alert(
				    event.title + " was moved " +
				    dayDelta + " days and " +
				    minuteDelta + " minutes."
				);

				if (allDay) {
				    alert("Event is now all-day");
				}else{
				    alert("Event has a time-of-day");
				}

				if (!confirm("Are you sure about this change?")) {
				    revertFunc();
				}
			},
			firstDay: 1,
			monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
			monthNamesShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
			dayNames: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
			dayNamesShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
			buttonText: {
			    prev:     '&nbsp;&#9668;&nbsp;',  // left triangle
			    next:     '&nbsp;&#9658;&nbsp;',  // right triangle
			    prevYear: '&nbsp;&lt;&lt;&nbsp;', // <<
			    nextYear: '&nbsp;&gt;&gt;&nbsp;', // >>
			    today:    'today',
			    month:    'month',
			    week:     'week',
			    day:      'day'
			},

			lazyFetching: true,
			eventSources: [

			     // your event source
			     {
				 url: 'calendar/dates',
				 type: 'POST',
				 cache: true,
				 data: {
				     custom_param1: 'something',
				     custom_param2: 'somethingelse'
				 },
				 error: function() {
				     alert('there was an error while fetching events!');
				 },
				 //color: 'yellow',   // a non-ajax option
				 textColor: 'black' // a non-ajax option
			     }

			     // any other sources...

			 ]
		});

	});

</script>
<style type='text/css'>
	#calendar {
		width: 900px;
		margin: 0 auto;
		}

</style>

<h2>Termine</h2>
<hr>

<div id='calendar'></div>