<link rel='stylesheet' type='text/css' href='fullcalendar/fullcalendar.css' />
<link rel='stylesheet' type='text/css' href='fullcalendar/fullcalendar.print.css' media='print' />

<script type='text/javascript' src='http://code.jquery.com/ui/1.10.1/jquery-ui.js'></script>
<link rel='stylesheet' type='text/css' href='http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css' />

<script type='text/javascript' src='fullcalendar/fullcalendar.min.js'></script>
<script type='text/javascript'>

	$(document).ready(function() {

		var date = new Date();
		var d = date.getDate();
		var m = date.getMonth();
		var y = date.getFullYear();

		$('#calendar').fullCalendar({
			header: {
				left: 'month,agendaWeek,agendaDay',
				center: 'title',
				right: 'today prev,next'
			},
			editable: true,
			selectable: true,
			unselectAuto: true,
			dayClick: function(date, allDay, jsEvent, view) {
				if (allDay) {
				    alert('Clicked on the entire day: ' + date);
				}else{
				    alert('Clicked on the slot: ' + date);
				}

				alert('Coordinates: ' + jsEvent.pageX + ',' + jsEvent.pageY);
				alert('Current view: ' + view.name);

				// change the day's background color just for fun
				$(this).css('background-color', 'red');
			},
			eventClick: function(calEvent, jsEvent, view) {
				alert('Event: ' + calEvent.title);
				alert('Coordinates: ' + jsEvent.pageX + ',' + jsEvent.pageY);
				alert('View: ' + view.name);

				// change the border color just for fun
				$(this).css('border-color', 'red');
			},
			eventResize: function(event,dayDelta,minuteDelta,revertFunc) {
				alert(
				    "The end date of " + event.title + "has been moved " +
				    dayDelta + " days and " +
				    minuteDelta + " minutes."
				);

				if (!confirm("is this okay?")) {
				    revertFunc();
				}
			},
			eventDrop: function(event,dayDelta,minuteDelta,allDay,revertFunc) {
				alert(
				    event.title + " was moved " +
				    dayDelta + " days and " +
				    minuteDelta + " minutes."
				);

				if (allDay) {
				    alert("Event is now all-day");
				}else{
				    alert("Event has a time-of-day");
				}

				if (!confirm("Are you sure about this change?")) {
				    revertFunc();
				}
			},
			events: [
				{
					title: 'All Day Event',
					start: new Date(y, m, 1)
				},
				{
					title: 'Long Event',
					start: new Date(y, m, d-5),
					end: new Date(y, m, d-2)
				},
				{
					id: 999,
					title: 'Repeating Event',
					start: new Date(y, m, d-3, 16, 0),
					allDay: false
				},
				{
					id: 999,
					title: 'Repeating Event',
					start: new Date(y, m, d+4, 16, 0),
					allDay: false
				},
				{
					title: 'Meeting',
					start: new Date(y, m, d, 10, 30),
					allDay: false
				},
				{
					title: 'Lunch',
					start: new Date(y, m, d, 12, 0),
					end: new Date(y, m, d, 14, 0),
					allDay: false
				},
				{
					title: 'Birthday Party',
					start: new Date(y, m, d+1, 19, 0),
					end: new Date(y, m, d+1, 22, 30),
					allDay: false
				},
				{
					title: 'Click for Google',
					start: new Date(y, m, 28),
					end: new Date(y, m, 29),
					url: 'http://google.com/'
				}
			]
		});

	});

</script>
<style type='text/css'>
	#calendar {
		width: 900px;
		margin: 0 auto;
		}

</style>

<h2>Termine</h2>
<hr>

<div id='calendar'></div>