<div class="content-box-subheader">
	<div class="tabs">
		<div<?php if($this->activetab == 'showmytasks') { ?> class="active"<?php } ?>><a href="./project/showmytasks"><?php echo $this->translate('my tasks'); ?></a></div>
		<div<?php if($this->activetab == 'showmyprojects') { ?> class="active"<?php } ?>><a href="./project/showmyprojects"><?php echo $this->translate('my projects'); ?></a></div>
		<div<?php if($this->activetab == 'showalltasks') { ?> class="active"<?php } ?>><a href="./project/showalltasks"><?php echo $this->translate('all tasks'); ?></a></div>
		<div<?php if($this->activetab == 'showallprojects') { ?> class="active"<?php } ?>><a href="./project/showallprojects"><?php echo $this->translate('all projects'); ?></a></div>
	</div>
</div>
