<?php include('include/header.phtml'); ?>

<div class="content-box">
	<?php include('include/menu.phtml'); ?>
	<?php include('include/tabs.phtml'); ?>
	<div class="content-box-body">
	<?php include('include/submenu.phtml'); ?>

	<table class="listing" width="100%" border="0" cellpadding="0" cellspacing="0">
		<tr class="listing-header">
			<td>Ticketid</td>
			<td>Projekt</td>
			<td>Firma</td>
			<td>Beginn</td>
			<td>Ende</td>
			<td>Prio</td>
			<td>Status</td>
		</tr>
		<tr class="listing-search-row">
			<td><input type="text" name="" value="" /></td>
			<td><input type="text" name="" value="" /></td>
			<td><input type="text" name="" value="" /></td>
			<td><input type="text" name="" value="" /></td>
			<td><input type="text" name="" value="" /></td>
			<td><input type="text" name="" value="" /></td>
			<td><input type="text" name="" value="" /></td>
		</tr>
	</table>

	</div>
</div>
