<?php include('include/header.phtml'); ?>

<div class="content-box">
	<?php include('include/menu.phtml'); ?>
	<?php include('include/tabs.phtml'); ?>
	<div class="content-box-body">
	<?php include('include/submenu.phtml'); ?>

Name: <?= $this->project['name'] ?><br />
Beschreibung: <?= $this->project['description'] ?><br />

	<table class="listing" width="100%" border="0" cellpadding="0" cellspacing="0">
		<tr class="listing-header">
			<td>Projektid</td>
			<td>Projekt</td>
			<td>Aufgabe</td>
			<td>Beginn</td>
			<td>Ende</td>
			<td>Prio</td>
			<td>Status</td>
			<td>Mitarbeiter</td>
		</tr>
		<tr class="listing-search-row">
			<td><input type="text" name="" value="" /></td>
			<td><input type="text" name="" value="" /></td>
			<td><input type="text" name="" value="" /></td>
			<td><input type="text" name="" value="" /></td>
			<td><input type="text" name="" value="" /></td>
			<td><input type="text" name="" value="" /></td>
			<td><input type="text" name="" value="" /></td>
			<td><input type="text" name="" value="" /></td>
		</tr>
<?php

if(is_array($this->tasks)) {
	$x = 0;
	foreach($this->tasks as $key => $value) {
		echo '<tr onmouseover="Element.addClassName(this,\'listing-row-over\');" onmouseout="Element.removeClassName(this,\'listing-row-over\');" onclick="window.location = \'./project/showproject/id/'.$value['id'].'\';" class="listing-row '.(($x == 0) ? 'listing-row-alternate' : '').'">
			<td>'.$value['id'].'</td>
			<td><a href="./project/showtask/id/'.$value['id'].'">'.$value['name'].'</a></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td><a href="./project/edittask/id/'.$value['id'].'" class="button">bearbeiten</a><a href="./project/deltask/id/'.$value['id'].'" class="button">l&ouml;schen</a></td>
		</tr>';
		if($x == 0) $x = 1;
		else $x = 0; 
	}
}
?>
	</table>

	</div>
</div>
